name: budgetpals_client
description: A mobile client for the budgetpals API.
version: 0.0.0+5
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  formz: ^0.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.0
  path_provider: ^2.0.14
  syncfusion_flutter_charts: ^22.2.11

dev_dependencies:
  build_runner: 
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
