name: budgetpals_client
description: A mobile client for the budgetpals API.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  api:
    path: packages/api
  auth_repository:
    path: packages/auth_repository
  bloc: ^8.1.0
  equatable: ^2.0.3
  expenses_repository:
    path: packages/expenses_repository
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  formz: ^0.6.0
  incomes_repository:
    path: packages/incomes_repository
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
