name: api
description: A Dart API Client for the budgetpals API.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.0
  path_provider: ^2.0.14

dev_dependencies:
  build_runner: 
  hive_generator: ^1.1.3