name: incomes_repository
description: Dart package which manages the incomes domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  api:
    path: ../api
  common_models:
    path: ../common_models
  equatable: ^2.0.0
