name: expenses_repository
description: Dart package which manages the expenses domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  api:
    path: ../api
  equatable: ^2.0.0
